# CMake generated Testfile for 
# Source directory: /home/pascal/ownCloud/MA/Code/test
# Build directory: /home/pascal/ownCloud/MA/Code/test/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(spline_test "spline_test")
add_test(autodiff_test "autodiff_test")
add_test(mat_util_test "mat_util_test")
add_test(opengl_cube_test "opengl_cube_test")
add_test(opengl_image_cube_test "opengl_image_cube_test")
add_test(opengl_ellipsoid_test "opengl_ellipsoid_test")
add_test(opengl_pyramid_test "opengl_pyramid_test")
add_test(manifold_son_test "manifold_son_test")
add_test(manifold_spd_test "manifold_spd_test")
add_test(manifold_grassmann_test "manifold_grassmann_test")
add_test(manifold_test "manifold_test")
add_test(data_test "data_test")
add_test(data3d_test "data3d_test")
add_test(data3d_slicing_test "data3d_slicing_test")
add_test(sphere_data_test "sphere_data_test")
add_test(son_data_test "son_data_test")
add_test(spd_data_test "spd_data_test")
add_test(dti_data_test "dti_data_test")
add_test(dti_data_test3d "dti_data_test3d")
add_test(functional_test "functional_test")
add_test(functional3d_test "functional3d_test")
add_test(brightness_functional_test "brightness_functional_test")
add_test(chromaticity_functional_test "chromaticity_functional_test")
add_test(tvmin_test "tvmin_test")
add_test(tvmin_test_prpt "tvmin_test_prpt")
add_test(tvmin_test_prpt3d "tvmin_test_prpt3d")
add_test(tvmin_test_irls3d "tvmin_test_irls3d")
add_test(error_computation_test_euc "error_computation_test_euc")
add_test(error_computation_test_son "error_computation_test_son")
add_test(error_computation_test_spd "error_computation_test_spd")
add_test(error_computation_test_sphere "error_computation_test_sphere")
add_test(inpaint_test "inpaint_test")
add_test(sphere_tvmin_test "sphere_tvmin_test")
add_test(sphere_tvmin_prpt_test "sphere_tvmin_prpt_test")
add_test(grassmann_chromaticnoise_test "grassmann_chromaticnoise_test")
add_test(son_functional_test "son_functional_test")
add_test(son_tvmin_test "son_tvmin_test")
add_test(son_tvmin_prpt_test "son_tvmin_prpt_test")
add_test(spd_tvmin_test "spd_tvmin_test")
add_test(dti_functional_test "dti_functional_test")
add_test(dti_tvmin_test "dti_tvmin_test")
add_test(dti_tvmin_prpt_test "dti_tvmin_prpt_test")
add_test(dti_tvmin_prpt_test3d "dti_tvmin_prpt_test3d")
add_test(dti_tvmin_irls_test3d "dti_tvmin_irls_test3d")
add_test(son_inpainting_test "son_inpainting_test")
add_test(son_fingerprint_test "son_fingerprint_test")
add_test(son_optical_flow "son_optical_flow")
add_test(colorization_test "colorization_test")
